github:
  collaborators: &id001
  - gharris1727
  - yashmayya
  - vcrfxia
  - lucasbru
  - philipnee
  - vamossagar12
  - fvaleri
  - clolov
  - hudeqi
  - andymg3
jenkins:
  github_whitelist: *id001
notifications:
  commits: commits@kafka.apache.org
  issues: jira@kafka.apache.org
  jira_options: link label
  pullrequests: jira@kafka.apache.org
