receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: "0.0.0.0:8890"
    namespace: default
    resource_to_telemetry_conversion:
      enabled: true
  otlp:
    endpoint: host.docker.internal:4320
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

