receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 10943040
        read_buffer_size: 10943040
        max_concurrent_streams: 200
        write_buffer_size: 10943040
      http:
        endpoint: 0.0.0.0:4318
  zipkin:
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: "0.0.0.0:8890"
    metric_expiration: 60s
    add_metric_suffixes: true
    resource_to_telemetry_conversion:
      enabled: false
  otlp:
    endpoint: host.docker.internal:4320
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus]
