{
 "title": "Detailed  Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(process_runtime_jvm_cpu_utilization_ratio,job)"
    }
   },
   {
    "name": "node_id",
    "label": "Node Id",
    "query": {
     "query": "label_values(process_runtime_jvm_cpu_utilization_ratio,instance)"
    }
   },
   {
    "name": "request_type",
    "label": "Kafka Request",
    "query": {
     "query": "label_values(kafka_request_count_total,type)"
    }
   },
   {
    "name": "s3stream_request",
    "label": "S3Stream Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Stream\"},operation_name)"
    }
   },
   {
    "name": "s3request",
    "label": "S3 Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Request\"},operation_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_cpu_utilization_ratio{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $C", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "NodeNode-{{instance}}#allocated"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_used_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#used"
    },
    { "expression": "1 - $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation Detailed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance, type) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_delta_wal_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Delta_WAL_Cache"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_block_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Block_Cache"
    }
   ]
  },
  { "title": "Kafka Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, job, type) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "IO Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_io_threads_idle_rate_1m{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Network Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_network_threads_idle_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  { "title": "KRaft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Current Leader",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_current_leader{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_current_epoch{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Quorum"
    },
    {
     "expr": "kafka_server_kraft_log_end_epoch{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Log"
    }
   ]
  },
  {
   "title": "KRaft Endoffset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_high_watermark{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#HW"
    },
    {
     "expr": "kafka_server_kraft_log_end_offset{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Log"
    }
   ]
  },
  {
   "title": "Append Record Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_append_records_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Record Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_fetch_records_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Record Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_commit_latency_avg_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_server_kraft_commit_latency_max_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Max"
    }
   ]
  },
  {
   "title": "Controller Event Queue Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(kafka_event_queue_time_milliseconds_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#Dequeue"
    },
    {
     "expr": "rate(kafka_event_queue_processing_time_milliseconds_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#Processing"
    }
   ]
  },
  {
   "title": "Controller Event Queueing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_event_queue_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_event_queue_time_max_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Max"
    },
    {
     "expr": "kafka_event_queue_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P50"
    },
    {
     "expr": "kafka_event_queue_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P99"
    }
   ]
  },
  {
   "title": "Controller Event Procsssing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_event_queue_processing_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_event_queue_processing_time_max_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Max"
    },
    {
     "expr": "kafka_event_queue_processing_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P50"
    },
    {
     "expr": "kafka_event_queue_processing_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P99"
    }
   ]
  },
  { "title": "S3Stream Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, operation_type) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "S3 Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation_name, instance) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "Delta WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal|append_wal_full\", operation_type=\"S3Storage\", stage=\"complete\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}_Avg"
    }
   ]
  },
  { "title": "Delta WAL Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache|append_log_cache_full\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Storage\", operation_name=\"read_log_cache\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_mean_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  { "title": "Upload WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Upload WAL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}"
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"read_block_cache\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_block_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_ahead\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (rate(kafka_stream_read_ahead_size_sum_bytes{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Read Ahead Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Read Ahead Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_ahead\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Size Avg",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(instance) (kafka_stream_read_ahead_size_mean_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Available Inflight Read Ahead Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_available_inflight_read_ahead_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "Total Bytes In / Out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_inbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_outbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  {
   "title": "Total Bytes In / Out (By Priority)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job, type) (rate(kafka_stream_network_inbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    },
    {
     "expr": "sum by(instance, job, type) (rate(kafka_stream_network_outbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_{{type}}"
    }
   ]
  },
  {
   "title": "Total Bytes In / Out (By Type)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_download_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_S3"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_upload_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_S3"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_Msg"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"out\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_Msg"
    }
   ]
  },
  {
   "title": "Network Inbound Throttle Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Network Outbound Throttle Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Network Inbound Throttle Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_inbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    }
   ]
  },
  {
   "title": "Network Outbound Throttle Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_outbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Out_{{type}}"
    }
   ]
  },
  { "title": "S3 Object", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "S3 Object Count Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 232 },
   "targets": [
    {
     "expr": "sum by(state) (kafka_stream_s3_object_count{job=\"$cluster_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Object Size Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_stream_s3_object_size_bytes{job=\"$cluster_id\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "StreamSetObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 244 },
   "targets": [
    {
     "expr": "sum by(node_id) (kafka_stream_stream_set_object_num{job=\"$cluster_id\", node_id=~\"$node_id\"})",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  },
  {
   "title": "StreamObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 244 },
   "targets": [
    {
     "expr": "kafka_stream_stream_object_num{job=\"$cluster_id\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Get Object Throughput By Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=\"get_object\", job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Get Object Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Get Object Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=\"get_object\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Throughput By Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Put Object Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Put Object Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\"})",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 282 } },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_compaction_read_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "rate(kafka_stream_compaction_write_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  { "title": "Auto-Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "Metrics Delay",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_auto_balancer_metrics_time_delay_milliseconds{job=\"$cluster_id\", node_id=~\"$node_id\"}",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  }
 ]
}