{
 "title": "automq-for-kafka",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_namespace)"
    }
   },
   { "name": "namespace", "query": "default_" },
   { "name": "prefix", "query": "kafka_stream_" },
   { "name": "OperationType", "query": "S3Stream,S3Storage,S3Request" },
   {
    "name": "node_id",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_instance_id)"
    }
   },
   {
    "name": "node_type",
    "query": {
     "query": "label_values(default_jvm_cpu_recent_utilization_ratio,service_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Kafka Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service_namespace, service_name, service_instance_id, type) (rate(${namespace}kafka_request_count_total{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{type}}"
    }
   ]
  },
  {
   "title": "Request Time Avg",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "${namespace}kafka_request_time_mean_milliseconds{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\", type=~\"Fetch|Produce\"}",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{type}}"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "${namespace}jvm_cpu_recent_utilization_ratio{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}",
     "legendFormat": "{{service_name}}_{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Heap Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B/$A\n", "type": "math" }
   ]
  },
  {
   "title": "JVM GC Monitor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name, service_instance_id, jvm_gc_action) (rate(${namespace}jvm_gc_duration_seconds_bucket{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}[$__rate_interval])))",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{jvm_gc_action}}"
    },
    {
     "expr": "sum by(jvm_gc_action, service_name, service_instance_id) (rate(${namespace}jvm_gc_duration_seconds_count{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_{{jvm_gc_action}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service_namespace, service_name, service_instance_id) (${namespace}jvm_memory_limit_bytes{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\", jvm_memory_type=\"heap\"})",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_limit"
    },
    {
     "expr": "sum by(service_namespace, service_name, service_instance_id) (${namespace}jvm_memory_used_bytes{service_namespace=\"$cluster_id\", service_name=~\"$node_type\", service_instance_id=~\"$node_id\", jvm_memory_type=\"heap\"})",
     "legendFormat": "{{service_name}}_{{service_instance_id}}_usage"
    }
   ]
  },
  { "title": "S3Stream Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "S3Stream Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(operation_name, operation_type) (rate(${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=~\"$OperationType\", operation_name!~\"append_wal|read_block_cache|read_log_cache\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval]))",
     "legendFormat": "{{operation_type}}_{{operation_name}}"
    }
   ]
  },
  {
   "title": "S3Stream Operation Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\", status=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3Stream Operation Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=~\"$OperationType\", operation_name!~\"append_wal|read_block_cache|read_log_cache\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_type}}_{{operation_name}}"
    }
   ]
  },
  { "title": "Delta WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Append Delta WAL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"append_log_cache|append_callback|append_wal_full\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}"
    },
    {
     "expr": "rate(${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"append_wal\", stage=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{stage}}"
    },
    {
     "expr": "rate(${namespace}${prefix}operation_count_total{operation_type=\"S3Storage\", operation_name=\"append_log_cache_full\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Append Delta WAL Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, stage) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"append_wal\", stage=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{stage}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=~\"append_callback|append_log_cache\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Read Delta WAL Cache Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=~\"read_log_cache\", status=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Delta WAL Cache Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=~\"read_log_cache\", status=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Delta WAL Size（DEBUG only）",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A - $B", "type": "math" },
    {
     "expr": "default_kafka_stream_delta_wal_cache_size_bytes{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "delta wal cache"
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Read Block Cache Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Storage\", operation_name=\"read_block_cache\", status=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Block Cache Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"read_block_cache\", status=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, status) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Storage\", operation_name=\"read_ahead\", status=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{operation_name}}_{{status}}"
    }
   ]
  },
  {
   "title": "Read Ahead Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(default_kafka_stream_read_ahead_size_bytes_sum{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "{{node_type}}_{{node_id}}"
    }
   ]
  },
  {
   "title": "Block Cache Size (DEBUG only)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${namespace}${prefix}block_cache_size_bytes{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Available Inflight Read Ahead Size (DEBUG only)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${namespace}${prefix}available_inflight_read_ahead_size_bytes{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "S3Stream Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}network_inbound_usage_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "inbound"
    },
    {
     "expr": "rate(${namespace}${prefix}network_outbound_usage_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "S3 Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}download_size_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "download"
    },
    {
     "expr": "rate(${namespace}${prefix}upload_size_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "S3Stream Network Available Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "${namespace}${prefix}network_inbound_available_bandwidth_bytes{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "inbound"
    },
    {
     "expr": "${namespace}${prefix}network_outbound_available_bandwidth_bytes{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "S3Stream Network Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_id, node_id, node_type) (rate(${namespace}${prefix}network_inbound_limiter_queue_time_nanoseconds_bucket{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "inbound"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_id, node_id, node_type) (rate(${namespace}${prefix}network_outbound_limiter_queue_time_nanoseconds_bucket{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Available S3 Inflight Quota (DEBUG only)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${namespace}${prefix}available_s3_inflight_read_quota{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "read"
    },
    {
     "expr": "${namespace}${prefix}available_s3_inflight_write_quota{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "S3 Network Limiter Queue Size (DEBUG  only)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${namespace}${prefix}network_inbound_limiter_queue_size{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "inbound"
    },
    {
     "expr": "${namespace}${prefix}network_outbound_limiter_queue_size{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}",
     "legendFormat": "outbound"
    }
   ]
  },
  { "title": "S3 Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "S3 Object Count Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}object_count_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "object_count"
    }
   ]
  },
  {
   "title": "Upload S3 Object Stage Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(stage, le) (rate(${namespace}${prefix}object_stage_cost_nanoseconds_bucket{stage=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Get Object Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 172 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(size) (${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=\"get_object\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetObject Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 3, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation_type, operation_name, size) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Request\", operation_name=\"get_object\", size=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 3, "x": 12, "y": 172 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(size) (${namespace}${prefix}operation_latency_nanoseconds_count{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"})",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, size) (rate(${namespace}${prefix}operation_latency_nanoseconds_bucket{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", size=~\".*\", service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])))",
     "legendFormat": "{{size}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(${namespace}${prefix}compaction_read_size_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "compaction_read"
    },
    {
     "expr": "rate(${namespace}${prefix}compaction_write_size_bytes_total{service_namespace=\"$cluster_id\", service_instance_id=~\"$node_id\", service_name=~\"$node_type\"}[$__rate_interval])",
     "legendFormat": "compaction_write"
    }
   ]
  }
 ]
}