# AutoMQ DevKit - ZeroZone Feature
# Layer 4: Enables zone router

automq.zonerouter.channels=0@s3://${S3_DATA_BUCKET}?region=${S3_REGION}&endpoint=${S3_ENDPOINT}&pathStyle=${S3_PATH_STYLE}&batchInterval=250&maxBytesInBatch=8388608
broker.rack=${AZ_NAME}
