# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Kafka on S3 - CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  checkstyle:
    name: "Checkstyle"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        jdk: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "zulu"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Checkstyle
        run: ./gradlew --build-cache rat checkstyleMain checkstyleTest
  spotbugs:
    name: "Spotbugs"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        jdk: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "zulu"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Spotbugs
        run: ./gradlew --build-cache spotbugsMain spotbugsTest
  test:
    name: "Unit Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        jdk: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "zulu"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Unit Test
        run: ./gradlew --build-cache metadata:S3UnitTest core:S3UnitTest s3stream:test
