name: AutoMQ Kafka Docker Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'AutoMQ Version Tag'
        required: false
        type: string
  workflow_run:
    workflows: ["GitHub Release"]
    types:
      - completed

env:
  KAFKA_VERSION: "3.9.0"

jobs:
  automq-kafka-release:
    name: AutoMQ Kafka Docker Image Release
    strategy:
      matrix:
        platform: [ "ubuntu-24.04" ]
        jdk: [ "17" ]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      -   name: Get release tag
          run: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
              TAG="${{ github.event.inputs.tag }}"
            # use the latest tag if not specified
            elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              TAG=$(git ls-remote --tags https://github.com/AutoMQ/automq.git | grep -v '\^{}' | tail -1 | sed 's/.*refs\/tags\///')
            else
              TAG="${{ github.event.workflow_run.head_branch }}"
            fi

            AUTOMQ_URL="https://github.com/AutoMQ/automq/releases/download/${TAG}/automq-${TAG}_kafka-${KAFKA_VERSION}.tgz"

            {
              echo "AUTOMQ_VERSION=${TAG}-kafka"
              echo "AUTOMQ_URL=${AUTOMQ_URL}"
            } >> $GITHUB_ENV

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_READ_WRITE_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          .venv/bin/pip install setuptools

          cd docker
          python3 docker_release.py \
            ${{ secrets.DOCKERHUB_USERNAME }}:${AUTOMQ_VERSION} \
            --kafka-url ${AUTOMQ_URL}
