name: E2E Docker Release

on:
  workflow_dispatch:

jobs:
  docker-release:
    name: Docker Image Release
    strategy:
      matrix:
        platform: [ "ubuntu-22.04" ]
        jdk: ["17"]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Image Tags
        id: image_tags
        run: |
          TAG=$(grep default_jdk tests/docker/ducker-ak | grep kos_e2e_base | awk -F ':|"' '{print $3}')
          echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/kos_e2e_base:$TAG" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_READ_WRITE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./tests/docker/base-Dockerfile
          push: true
          tags: ${{ steps.image_tags.outputs.tags }}
          platforms: linux/amd64,linux/arm64
