name: AutoMQ Helm Chart Release

on:
  workflow_call:
    inputs:
      uploadToRelease:
        required: true
        default: false
        type: boolean
      env:
        required: true
        default: Test
        type: string
  workflow_dispatch:
    inputs:
        uploadToRelease:
          description: 'Upload Result to Release'
          required: true
          default: false
          type: boolean
        env:
          description: 'Environment'
          required: true
          default: Test
          type: choice
          options:
            - Test
            - Prod

jobs:
  helm-chart-release:
    name: Docker Image Release
    strategy:
      matrix:
        platform: [ "ubuntu-22.04" ]
        registry: ["automq-docker-registry-registry.cn-hangzhou.cr.aliyuncs.com"]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Change Chart Version
        id: change_chart_version
        run: |
          LATEST_TAG=$(grep -Po "version = '\K.*?(?=')" build.gradle | head -n 1)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          if [ ${{ inputs.env }} == "Prod" ]; then
            echo "CHART_VERSION=${LATEST_TAG}"
            echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
            sed -i "s/^version: .*/version: ${LATEST_TAG}/; s/^appVersion: .*/appVersion: ${LATEST_TAG}/" chart/Chart.yaml
          else
            CHART_VERSION=${LATEST_TAG}-snapshot.${TIMESTAMP}
            echo "CHART_VERSION=${CHART_VERSION}"
            echo "version=${CHART_VERSION}" >> $GITHUB_OUTPUT
            sed -i "s/^version: .*/version: ${CHART_VERSION}/; s/^appVersion: .*/appVersion: ${CHART_VERSION}/" chart/Chart.yaml
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      - name: Push Helm Chart
        env:
          HELM_REPO_USERNAME: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }}
        run: |
          helm plugin install https://github.com/AliyunContainerService/helm-acr
          helm repo add automq acr://automq-docker-registry-chart.cn-hangzhou.cr.aliyuncs.com/automq/automq --username ${HELM_REPO_USERNAME} --password ${HELM_REPO_PASSWORD}
          helm cm-push chart automq -f

      - name: Output Artifact ID
        if: ${{ inputs.uploadToRelease }}
        run: |
          cd ./chart
          touch helm_chart_version_${{ steps.change_chart_version.outputs.version }}.json
          echo "{"tag": "${{ steps.change_chart_version.outputs.version }}"}" > helm_chart_version_${{ steps.change_chart_version.outputs.version }}.json

      - name: Update Release
        if: ${{ inputs.uploadToRelease }}
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: AutoMQ Kafka ${{ github.ref_name }}-branch-build
          tag: ${{ github.ref_name }}
          artifacts: "chart/*.json"
          artifactContentType: "tgz"
          replacesArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
