name: Nightly E2E tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  run_e2e:
    name: "Run E2E tests"
    runs-on: [ self-hosted, e2e ]
    env:
      TC_GENERAL_MIRROR_URL: "mirrors.ustc.edu.cn"
      ESK_TEST_YML: "tests/kos_test_suite.yml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Clean last running results
        run: |
          rm -rf results
      - name: Run E2E tests
        run: ./tests/docker/run_tests.sh
      - name: Report results
        run: python3 tests/report_e2e_results.py
        env:
          WEB_HOOK_URL: ${{ secrets.E2E_REPORT_WEB_HOOK_URL }}
          SHOW_RESULTS_URL: ${{ secrets.E2E_REPORT_SHOW_RESULTS_URL }}
      - name: Bring down docker containers
        run: bash ./tests/docker/ducker-ak down
        if: ${{ always() }}