name: Nightly E2E tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  core_e2e:
    name: "Run Main E2E Tests(core_tools_client_sanity)"
    uses: ./.github/workflows/e2e-run.yml
    with:
      suite-id: "main"
      test-yaml: "tests/main_kos_test_suite.yml"
      storage-path: "/data/github-actions/reports"
  extra_e2e:
    name: "Run extra E2E Tests(connect_streams_benchmarks)"
    uses: ./.github/workflows/e2e-run.yml
    with:
      suite-id: "extra"
      test-yaml: "tests/extra_kos_test_suite.yml"
      storage-path: "/data/github-actions/reports"
  e2e_summary:
    name: "E2E Tests Summary"
    runs-on: [ self-hosted, e2e ]
    needs: [ core_e2e, extra_e2e ]
    steps:
      - name: Report results
        run: python3 tests/report_e2e_results.py
        env:
          WEB_HOOK_URL: ${{ secrets.E2E_REPORT_WEB_HOOK_URL }}
          SHOW_RESULTS_URL: ${{ secrets.E2E_REPORT_SHOW_RESULTS_URL }}
          STORAGE_PATH: "/data/github-actions/reports"