name: Nightly Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  publish:
    name: "Publish"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        jdk: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "zulu"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew releaseTarGz --refresh-dependencies
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: nightly
          name: 'Kafka on S3 Nightly Release $$'
          draft: false
          prerelease: true
          body: |
            This is a nightly release of Kafka on S3.
            It's unstable compared to the official releases, **use it with caution**!
          files: |
            ./core/build/distributions/kafka_*[^a-z].tgz
