name: Nightly E2E tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run_e2e:
    name: "Run E2E tests"
    runs-on: [ self-hosted, e2e ]
    env:
      TC_GENERAL_MIRROR_URL: "mirrors.ustc.edu.cn"
      ESK_TEST_YML: "tests/kos_test_suite.yml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clean last run results
        run: |
          rm -rf results
      - name: Run E2E tests
        run: bash ./tests/docker/run_tests.sh
      - name: Bring down dockers
        run: bash ./tests/docker/ducker-ak down