name: Testing E2E actions
on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: 'Runs on'
        required: false
        default: main
        type: choice
        options:
          - main
          - main-release
  schedule:
    - cron: '0 16 * * *'

jobs:
  e2e1:
    name: "Run E2E Tests-1"
    uses: ./.github/workflows/e2e-run.yml
    # if: ${{ github.repository_owner == 'AutoMQ' }}
    with:
      suite-id: "e2e1"
      test-path: "tests/kafkatest/tests/core/get_offset_shell_test.py::GetOffsetShellTest.test_get_offset_shell_topic_pattern"
      storage-path: "/mnt/reports"
      runner: ${{ inputs.runs_on || 'main' }}
  e2e2:
    name: "Run E2E Tests-2"
    uses: ./.github/workflows/e2e-run.yml
    # if: ${{ github.repository_owner == 'AutoMQ' }}
    with:
      suite-id: "e2e2"
      test-path: "tests/kafkatest/tests/core/get_offset_shell_test.py::GetOffsetShellTest.test_get_offset_shell_topic_name"
      storage-path: "/mnt/reports"
      runner: ${{ inputs.runs_on || 'main' }}
  job2:
    runs-on: ${{ inputs.runs_on || 'main' }}
    needs: [ e2e1, e2e2 ]
    steps:
      - env:
          OUTPUT1: ${{needs.e2e1.outputs.output1}}
          OUTPUT2: ${{needs.e2e2.outputs.output1}}
        run: |
          echo "Artifact ID from e2e1 job is $OUTPUT1"
          echo "Artifact ID from e2e2 job is $OUTPUT2"
  e2e_summary:
    runs-on: ${{ inputs.runs_on || 'main' }}
    name: "E2E Tests Summary"
    if: ${{ always() }}
    # if: ${{ always() && github.repository_owner == 'AutoMQ' }}
    needs: [ e2e1, e2e2 ]
    steps:
      - name: Report results
        run: python3 tests/report_e2e_results.py
        env:
          WEB_HOOK_URL: ${{ secrets.E2E_REPORT_WEB_HOOK_URL }}
          SHOW_RESULTS_URL: ${{ secrets.E2E_REPORT_SHOW_RESULTS_URL }}
          STORAGE_PATH: "/data/github-actions/reports"
          REPORT_TITLE_PREFIX: "Main"
